import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DemoBanner } from "@/components/DemoBanner";
import Providers from "./providers";
import { CommandPalette } from "@/components/CommandPalette";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { Toaster } from "sonner";
import { DemoTour } from "@/components/DemoTour";
import { HeaderActions } from "@/components/HeaderActions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <a href="#main" className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:bg-background focus:text-foreground focus:border px-3 py-1 rounded">
          Pular para o conteúdo
        </a>
        <header className="w-full border-b bg-background">
          <div className="mx-auto max-w-7xl px-6 py-4 flex items-center justify-between gap-4">
            <div className="flex items-center gap-6">
              <div className="font-semibold">Imobgest – Demo</div>
              {/* role-based nav (mock) */}
              <Nav />
            </div>
            <HeaderActions />
          </div>
        </header>
        <Providers>
          <main id="main" className="mx-auto max-w-7xl px-6 py-6 space-y-4" role="main">
            <DemoBanner />
            <Breadcrumbs />
            {children}
          </main>
          <CommandPalette />
          <DemoTour />
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}

function Nav() {
  // client-only bits are avoided here; use basic links, hide per role using CSS via data-attr on body would be ideal.
  // Keep nav simple and visible; RoleGuard still protects routes.
  return (
    <nav className="text-sm flex items-center gap-4">
      <Link href="/" className="hover:underline">Dashboard</Link>
      <Link href="/feed" className="hover:underline">Feed</Link>
      <Link href="/contratos" className="hover:underline">Contratos</Link>
      <Link href="/imoveis" className="hover:underline">Imóveis</Link>
      <Link href="/mapa" className="hover:underline">Mapa</Link>
      <Link href="/sitemap" className="hover:underline">Sitemap</Link>
      <Link href="/relatorios/inadimplencia" className="hover:underline">Relatórios</Link>
      <Link href="/financeiro/boletos" className="hover:underline">Boletos</Link>
      <Link href="/financeiro/repasses" className="hover:underline">Repasses</Link>
      <Link href="/manutencoes" className="hover:underline">Manutenções</Link>
      <Link href="/correspondencias" className="hover:underline">Correspondências</Link>
      <Link href="/avisos" className="hover:underline">Avisos</Link>
      <Link href="/admin" className="hover:underline">Admin</Link>
      <Link href="/inquilino" className="hover:underline">Inquilino</Link>
      <Link href="/proprietario" className="hover:underline">Proprietário</Link>
    </nav>
  );
}
